version: "3.8"

services:
  drf: 
    build:
      context: .
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DEBUG=1
      - SHIPPING_COSTS_URL=https://random.api.randomkey.io/v1/double
      - SHIPPING_COSTS_KEY=96aac0784de8fc3aed39c0daffc5f8ed
      - REDIS_DB=0
      - REDIS_DEFAULT_TTL=10
      - REDIS_HOST=redis
      - REDIS_LOCATION=redis://redis:6379/0
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:8000
  redis:
    image: "redis:alpine"